---
title: 'Reduce computation cost: smaller AOI'
author: "Tze-Li Liu"
date: "6/4/2021"
output: html_document
---
```{R message=FALSE, warning=FALSE}
library(stars) ; library(sf) 
library(dplyr)
library(ggplot2)
```

```{R echo = FALSE}
knitr::opts_knit$set(root.dir = "/Masterarbeit/analysis")
```

I am trying to reduce the computation cost required to preprocess the 100*100m raster files as well as the storage space. The first possibility is to reduce the area of the data. 

## Load the boundary shapefiles

```{R}
Swiss <- st_read("1_data/raw/Switzerland_shapefile/CHE_adm1.shp") %>% 
  st_transform(st_crs(2056)) %>% 
  summarize

# AOI (national boundary + 50km buffer)
AOI <- st_read("1_data/raw/Switzerland_shapefile/AOI_4326.shp") %>% 
  st_transform(st_crs(2056))
```

## Compare the area of the bounding box

Originally when I was downloading the datasets, I assigned a buffer of 50km outside of the Swiss boundary to avoid unexpected exclusion of pixels, particularly for the datasets with coarse spatial resolutions. 

```{R fig.width = 7 , fig.height = 3}
AOI_bbox <- AOI %>% 
  st_bbox() %>% st_as_sfc()
Swiss_bbox <- Swiss %>% 
  st_bbox() %>% st_as_sfc()
ggplot() +
  geom_sf(data = AOI_bbox , fill = "dodgerblue4" , alpha = 0.9) +
  geom_sf(data = AOI , fill = NA , color = "white") +
  geom_sf(data = Swiss_bbox , fill = "dodgerblue" , alpha = 0.4) +
  geom_sf(data = Swiss , fill = NA , color = "white") +
  theme_bw()
```

The buffered AOI, however, introduces an expansion in the data size of the `stars` objects. `stars` objects contains the values of every pixels within the bounding box of the AOI. We can calculate the areas of the bounding box of the Swiss boundary `Swiss` and the 50-km-buffered AOI `AOI`. 

```{R}
st_area(Swiss_bbox) / st_area(AOI_bbox)
```

The area of the bounding box (aka the coverage of `stars` objects) of `Swiss` is only 53% of that of the 50-km-buffered AOI. 

## Compare the size of the `stars` objects

First rasterize the two areas into `stars`, then compare the object sizes: 

```{R}
AOI_grid100 <- AOI %>% 
  st_rasterize(crs = st_crs(2056) , dx = 100 , dy = 100) 
Swiss_grid100 <- Swiss %>% 
  summarize() %>% 
  st_rasterize(crs = st_crs(2056) , dx = 100 , dy = 100)

lobstr::obj_size(Swiss_grid100)/lobstr::obj_size(AOI_grid100)
```

The size of the `stars` object of the Swiss boundary is only 53% of that of the 50-km-buffered AOI, proportional to the area of the bounding box of the area of interest.   

## Conclusion

Since we are working at finer resolution now (1km to 100m), the 50-km buffer is not really necessary but consumes much more storage space and poses higer cost for computation. Therefore for preparing the final datasets for the model input, I would **reset the AOI to a buffered area of only 5km** (allowing moving window summation for the boundary pixels) to reduce data sizes. 





